import Head from 'next/head'
import Image from 'next/image'
import { Col, Container, Row } from 'react-bootstrap'
import Nav from '../components/Nav'
import Slater from '../components/Slater'
import speaker1 from '../speaker1.svg'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Plotline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Container>
        <Row className='my-3'>
        <h3 style={{ fontWeight: '500',color:'#091E42',opacity:'0.7' }}>John Doe Interview</h3>

        </Row>
        <Row className='my-3'>
          <Slater />
        </Row>
        <div style={{width:'60%',backgroundColor:'#F4F5F7',marginLeft:'5%',borderRadius: '10px 10px 0px 0px'}} className='mb-5'>
         
            <h6 className='mx-3 py-1'>Box 1</h6>
  
          <div className='py-1 d-inline-flex fluid px-3' style={{height:'39px'}}>
            <div>
            <Image src={speaker1} className='rounded-circle'  alt=""/>
            </div>
            <div>
            <h6 className='my-auto mx-2 text-center py-2'>Speaker 1</h6>
            </div>
            <div>
            <p className='px-auto mx-2 py-1' style={{opacity:'0.6',fontWeight:'400'}}>09:45</p>
            </div>
          </div>
          <Row>
            <p className='px-5'>
            There are many variations of Lorem Ipsum but the majority have suffered alteration There are many variation passa dont look even slightly believable. If you are going to use a passage.
            </p>
          </Row>
        
       

       <div className='py-1 d-inline-flex fluid px-3' style={{height:'39px'}}>
         <div>
         <Image src={speaker1} className='rounded-circle'  alt=""/>
         </div>
         <div>
         <h6 className='my-auto mx-2 text-center py-2'>Speaker 2</h6>
         </div>
         <div>
         <p className='px-auto mx-2 py-1' style={{opacity:'0.6',fontWeight:'400'}}>06:35</p>
         </div>
       </div>
       <Row>
         <p className='px-5'>
         There are many variations of Lorem Ipsum but the majority have suffered alteration There are many variationpassa
dont look even slightly believable. If you are going to use a passage.
         </p>
       </Row>

       <div className='py-1 d-inline-flex fluid px-3' style={{height:'39px'}}>
         <div>
         <Image src={speaker1} className='rounded-circle'  alt=""/>
         </div>
         <div>
         <h6 className='my-auto mx-2 text-center py-2'>Speaker 3</h6>
         </div>
         <div>
         <p className='px-auto mx-2 py-1' style={{opacity:'0.6',fontWeight:'400'}}>04:30</p>
         </div>
       </div>
       <Row>
         <p className='px-5'>
         There are many variations of Lorem Ipsum but the majority have suffered alteration There are many variationpassa
dont look even slightly believable. If you are going to use a passage.
         </p>
       </Row>
  </div>
        </Container>


     
     
    </div>
  )
}
